let num1 = prompt('write a number')
console.log(num1)
num1=Number(num1)
let num2 = prompt('write another number')
console.log(num2)
num2=Number(num2)
alert(`Result ${num1+num2}`)

let num3 = prompt('write a number')
num1=Number(num1)
let num4 = prompt('write another number')
num2=Number(num2)
alert(`Result ${num3-num4}`)

let num5 = prompt('write a number')
num1=Number(num1)
let num6 = prompt('write another number')
num2=Number(num2)
alert(`Result ${num5*num6}`)

let num7 = prompt('write a number')
num1=Number(num1)
let num8 = prompt('write another number')
num2=Number(num2)
alert(`Result ${num7/num8}`)